# Generated by Django 4.2.2 on 2023-07-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='num',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
